### ISSUE TITLE
'Method not found' exception when using context menu

### ISSUE THREAD

**Issue by jasonaughton** [Visual-Stylecop/Visual-StyleCop#16]
When running StyleCop from the right-click context menu on a Solution Explorer item or on the file itself, I get a model dialog with the following message:

Method not found: 'Void StyleCop.CodeProject.ctor(Int32, System.String, StyleCop.Configuration, Double).

Version is 4.7.55.26 in VS2015 Enterprise

**Comment by ptittof57** [comment]
@jasonaughton do you get this message each time you use the right-click context menu ?
Which kind of project you try to run StyleCop ?

**Comment by jasonaughton** [comment]
I get this irrespective of what I right-click - on the solution, any project type and all C# files. Have removed and reinstalled the extension, the problem remains.

**Comment by ptittof57** [comment]
It seems that your version try to load an old version of StyleCop.dll. 
I updated the constructor since version 4.7.52.0.

Try to uninstall again and search for "StyleCop.dll" in folder / C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions and check the version. Remove previous versions manually if necessary.

Then run VS2015 as admin and try to reinstall.

Let me know if you need more help.

**Comment by jasonaughton** [comment]
I am using StyleCop 4.7.49

Where can I get 4.7.52? I've not been able to find that version.

**Comment by ptittof57** [comment]
4.7.49 is the version from original codeplex and doesn't support VS2015. I think this dll shouldn't be in folder C:\Program Files (x86)\Microsoft Visual Studio 14.0

Uninstall version 4.7.49 and delete all references in C:\Program Files (x86)\Microsoft Visual Studio 14.0 and reinstall version [4.7.55.26](https://visualstudiogallery.msdn.microsoft.com/cac2a05b-6eb6-4fa2-95b9-1f8d011e6cae), it should work.

There is no direct download for previous versions but I am working on that for next releases.

**Comment by jasonaughton** [comment]
I tried that and it worked. However, I had to update the Resharper.Stylecop extension to use the 4.7.55 version, and once that was done the Resharper integration no longer worked. 

I'm going to leave this for now and continue to rely on Resharper with 4.7.49.

**Comment by ptittof57** [comment]
No fix available for now, current version of Visual StyleCop is incompatible with R# plugin.

**Comment by readingdancer** [comment]
Hi, I just thought I would add a comment to say we have been using R# and Stylecop since they first worked together. Do you know what would be required to make this new version compatible with the latest version of R# 10 as it's a bit of a show stopper for us using it. We'd potentially be happy to help if we can with either testing or even coding if we can find the time :)

**Comment by ptittof57** [comment]
Hi @readingdancer, I think to work with R#10 and Visual-StyleCop you should create a fork and a new project based on StyleCop CodexPlex sources.
In the current repo, I removed R# because I don't have a license to test it. Another solution maybe is to try https://github.com/StyleCop/StyleCop that should support R#.
