### ISSUE TITLE
Unable to display the StyleCop Rule help documentation

### ISSUE THREAD

**Issue by oneheed** [Visual-Stylecop/Visual-StyleCop#94]
![image](https://user-images.githubusercontent.com/18730285/41464075-8227ec7a-70cb-11e8-9a93-8690e7c86b10.png)

![image](https://user-images.githubusercontent.com/18730285/41464097-9a8aaf96-70cb-11e8-8655-441138dc2686.png)

i use visual studio 2017

**Comment by sonergonul** [comment]
Looks like this error thrown because of this line;

https://github.com/StyleCop/StyleCop/blob/775863c5616d303034bf2f5b0aa244f510e56453/Project/Src/StyleCop.VisualStudio/VSIntegration/ViolationTask.cs#L263

which looks like can't find the path that "Docs\\StyleCop.chm" file exists. Can you try to run your VS as administrator as well? Or maybe finding manually this file somehow?

**Comment by thehumblestart** [comment]
Has anyone know this problem?
Because I have same problem to.
